### ISSUE TITLE
Please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [SamarthDesai01/RepeatMe#1]
With v1.2.0 still having `versionCode:1` as v1.1.1 had it, it seems you're never increasing this value. But that's the setting Android uses to tell versions apart and seeing which is newer and thus an update. Could you please start increasing `versionCode` with each new version?

**Comment by SamarthDesai01** [comment]
Oh sorry about that! I've been increasing the version code for the Play Store build but forgot to reflect these changes here. Thanks for letting me know!

**Comment by SamarthDesai01** [comment]
Latest push now has the correct version code, please let me know if there are any other issues!

**Comment by IzzySoft** [comment]
That I can tell as soon as the next APK is published :rofl: Thanks a lot for your fast response! I had planned to serve your app via [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid) if you don't mind (for those who prefer not to use Playstore, or cannot use it). If my scanners give a thumbs-up, I could even try to get it into the official repo if you agree.

**Comment by SamarthDesai01** [comment]
Just published the latest release! I'd be more than happy to see my app on your repo, as long as there's a link to the original source you're all good to go! 👍

**Comment by IzzySoft** [comment]
I happily oblige! And having links to the original source is a mandatory thing for an open-source repo anyway, so skipping that is out of the question for me.

But take a look for yourself: [here it is](https://apt.izzysoft.de/fdroid/index/apk/com.samarthdesai.repeatme). Feel free to point to my repo for your app, so "Anti-Googlers" can pick it from there and be kept up-to-date if they do so using the F-Droid client.

Shall I proceed to bring it into the official F-Droid repo? Looks like it would be welcomed there with open arms, from what I can see (not being an Android dev myself).

PS: Also find your app [here](https://android.izzysoft.de/applists/category/named/office_todo#group_26) now :wink:

Uh, what has [VT to complain](https://www.virustotal.com/de/file/24d2f81fce57e78e8a8da1fc4a3aa6a1201eb60c91ef0037e7b6c1fd8a293d01/analysis/1533848617/)? PUP (Possibly Unwanted Program)? What a Babable!

**Comment by SamarthDesai01** [comment]
Looks great! I've added a link to your repo, it'd be great to see it on the official F-Droid repo too!

I'm not sure what's causing Babable to act up, does it state any reason for why it's a PUP? 
Thankfully every other scan looks good.

**Comment by IzzySoft** [comment]
> Looks great! I've added a link to your repo,

Cool :clap: :tada:

> it'd be great to see it on the official F-Droid repo too!

[Here you go](https://gitlab.com/fdroid/rfp/issues/687), I've just filed the RFP (Request For Packaging). Might take a little, though. In a few hours the bot will check your repo and report its findings – and if all's green, a developer will process it (or otherwise ask you for some adjustments).

> I'm not sure what's causing Babable to act up, does it state any reason for why it's a PUP?

I'm puzzled as well – and no, that's the problem. At least I didn't figure out yet. I'll trigger a rescan in a few days, hoping it either had its outdated signatures updated (check the timestamp, they're relly not fresh) or was removed. Ping me if you didn't hear back from me on that within, say, 10 days.

> Thankfully every other scan looks good.

Yeah, that's why it got the "Notif" icon only (next stage would be "warn", then "alert" – and with "alert" I usually unlist an app (make it invisible until clarified). And usually it ~is~ was WhiteArmor throwing those incomprehensible PUP/PUA stuff (which is most likely why that engine got removed finally, which I'm glad for) …

**Comment by SamarthDesai01** [comment]
Thanks for filing everything! I never would've thought of putting it on F-droid myself.

Seems WhiteArmor is just acting up then, I'll be sure to check back with you for any updates once everything gets updated on their end. It's great that they removed the engine based on what you've told me 😆

**Comment by IzzySoft** [comment]
It acted up a bit too often :laughing:

Let's see. As old as their signatures are, that engine might even get removed for that reason alone. I'll give it 5 days, then try a rescan, and if needed another one after another 5 days. Then hopefully your app is ready to appear in the official repo (well, dreaming is permitted – I rather guess some 3 weeks until then), and the issue is obsolete.

**Comment by SamarthDesai01** [comment]
Here's hoping everything goes through in a reasonable amount of time 😆
