### ISSUE TITLE
Problem with clock change

### ISSUE THREAD

**Issue by ricerox** [SamarthDesai01/RepeatMe#14]
Last sunday the summer time started in Europe ( so it's now an hour later). 
Since that day all the notification come an hour to late. I think this happens because the notification is still sent with the old time. When creating a new notification it appears at the right time.

I tried to reproduce this behaviour by changing time zones but it didn't behave the same way. 

I hope you can do something with this.

**Comment by ricerox** [comment]
Strangely it works correctly now. This could have happened because of the manual change of the time (zone).

**Comment by SamarthDesai01** [comment]
That's good to hear! I noticed this issue as well earlier, but I think the manual timezone change is the only way to guarantee a fix. Unfortunately, scheduling notifications and handling the timezone changes is something that isn't explicitly in my control so I'm not sure what I could do to prevent it from happening. I'll try looking into potential solutions.

**Comment by ricerox** [comment]
Ok. Since that not a problem with your app, I will close this issue.

**Comment by protist** [comment]
I got bitten with this today too. DST changed overnight, and the notification was still in the old time. I tried to edit the notification, but I couldn't work out how to do that. Issue #2 suggests that we should now be able to edit the items, but I can't find a way to do this?
