### ISSUE TITLE
Feature request: change notification sound

### ISSUE THREAD

**Issue by moso** [SamarthDesai01/RepeatMe#3]
As per the current version, I can't change the notification sound for a/each reminder. The ability to change notification sound per reminder would be really nice.

**Comment by SamarthDesai01** [comment]
From what I know, I don't believe the notification plugin I'm using allows me to control the notification sound. That appears to be an Android system level control and one which I don't have access to inside Flutter. 

If you think there's a solution or something I may be overlooking please let me know!

**Comment by moso** [comment]
I guess this can be solved on Android level, as you can select notification per app.

My initial idea was more to be able to distinguish reminders from each other with different notification sounds per reminder.

I'm not aware of any plugins, as I'm not an Android developer. I only do web :sweat_smile:

**Comment by SamarthDesai01** [comment]
So I decided to look further in to it and apparently it is possible to specify a custom notification sound. However with the way Google has made changes in the way notifications are handled starting with Android Oreo, any custom changes one makes to a notification will warrant creating a new notification channel.

Once this channel is created we can't make any further changes to its behavior meaning each notification sound would need its very own channel and soon we'd have to deal with way too many of those.

This might make it really confusing for the end user when accessing Settings and having 30+ channels to choose from and not knowing which notification corresponds with which channel 😆 

Hopefully Google relaxes this behavior in the future, but until then I'll keep this feature request in mind when looking for other ways to update the app! 👍
