### ISSUE TITLE
How does one build the "release"?

### ISSUE THREAD

**Issue by licaon-kter** [SamarthDesai01/RepeatMe#5]
Issue: https://forum.f-droid.org/t/repeat-me/5215/2

Metadata that builds "release" by default: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.samarthdesai.repeatme.yml#L29

Gradle with no debug flavour: https://github.com/SamarthDesai01/RepeatMe/blob/master/android/app/build.gradle#L35

Ping @Rudloff

**Comment by SamarthDesai01** [comment]
I believe setting the flutter.buildMode tag to "release" should force it to always build in release mode. It can be found in the following file below

[https://github.com/SamarthDesai01/RepeatMe/blob/93a14d0cbda5fb0ced4023ec284041afb8e42026/android/local.properties](https://github.com/SamarthDesai01/RepeatMe/blob/93a14d0cbda5fb0ced4023ec284041afb8e42026/android/local.properties)

**Comment by licaon-kter** [comment]
In the meantime, what does this error mean?
```
INFO: Running 'build' commands in build/com.samarthdesai.repeatme
ERROR: Could not build app com.samarthdesai.repeatme: Error running build command for com.samarthdesai.repeatme:1.2.5
==== detail begin ====
+ ../srclib/flutter/bin/flutter config --no-analytics
Analytics reporting disabled.
+ ../srclib/flutter/bin/flutter build apk
Initializing gradle...
compiler message: file:///home/vagrant/.pub-cache/hosted/pub.dartlang.org/flutter_material_color_picker-0.0.5/lib/src/material_color_picker.dart:50:4: Error: Getter not found: 'protected'.
compiler message:   @protected
compiler message:    ^
compiler message: file:///home/vagrant/.pub-cache/hosted/pub.dartlang.org/flutter_material_color_picker-0.0.5/lib/src/material_color_picker.dart: Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
compiler message: file:///home/vagrant/.pub-cache/hosted/pub.dartlang.org/flutter_material_color_picker-0.0.5/lib/src/circle_color.dart:15:6: Error: Getter not found: 'required'.
compiler message:     @required this.color,
compiler message:      ^
compiler message: file:///home/vagrant/.pub-cache/hosted/pub.dartlang.org/flutter_material_color_picker-0.0.5/lib/src/circle_color.dart: Error: This can't be used as metadata; metadata should be a reference to a compile-time constant variable, or a call to a constant constructor.
compiler message: file:///home/vagrant/.pub-cache/hosted/pub.dartlang.org/flutter_material_color_picker-0.0.5/lib/src/circle_color.dart:16:6: Error: Getter not found: 'required'.
compiler message:     @required this.circleSize,
compiler message:      ^
Compiler terminated unexpectedly.
```

Ref: https://f-droid.org/wiki/page/com.samarthdesai.repeatme/lastbuild_6

**Comment by SamarthDesai01** [comment]
It appears that the new color picker that was added with v1.2.5 is causing issues during compile time. I'm not exactly sure how to fix this though as I never touched any of the code for the color picker. Are you sure your version of Dart and Flutter are updated to the latest versions? This was necessary for me to do so before I could integrate the new color picker into the app.

**Comment by SamarthDesai01** [comment]
I notice that the latest update made its way to F-droid, do you know what eventually fixed the issue?

**Comment by licaon-kter** [comment]
It wasn't about the build itself, but about building it without the internet permission. 

Since you'll remove that in the next version, I consider it fixed.
